[package]
name = "quagga"
version = "0.1.1"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
ignore = "0.4"

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.1"

